### ISSUE TITLE
Do not show the interfaces, that definitely does not work

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.kisshome-research#37]
Make a list of such a interfaces to filter them out

**Comment by enigmax96** [comment]
- captured on Fritz!Box Cable 6490 Cable 
- on the capture interface (not in Kisshome Instance)
- captured for 10 seconds per interface, without capture filter


| Interface   | Return       |
|-------------|--------------|
| acc0        | 27,2 MB       |
| acc0.4      | 4,5 KB        |
| l2sd0.2     | 76,7 KB       |
| ~~l2sm0~~   | ~~0 Bytes~~   |
| acc0        | 23,1 KB       |
| ~~acc0.4~~  | ~~0 Bytes~~   |
| eth0        | 182 KB        |
| ~~eth1~~    | ~~0 Bytes~~   |
| eth2        | 186 KB        |
| ~~eth3~~    | ~~0 Bytes~~   |
| eth_udma0   | 137 KB        |
| lan         | not tested    |
| ~~ppptty~~  | ~~0 Bytes~~   |
| traceDH0    | 3,5 MB        |
| traceDH2    | 30,7 KB       |
| traceDL0    | 264 KB        |
| traceDL2    | 15,5 KB       |
| traceN0     | 766 KB        |
| traceV0     | 382 KB        |
| traceV1     | 37,8 KB       |
| vlan_master0| 241 KB        |
| wifi0   | 0 KB (my wifi is not running on this FritzBox) |
| wifi1   | 0 KB (my wifi is not running on this FritzBox) |
