### ISSUE TITLE
Nach Zufügen von Geräten keine Speicherung möglich

### ISSUE THREAD

**Issue by zahnheinrich** [ioBroker/ioBroker.kisshome-research#57]
In der Adressliste bleiben die Felder SPEICHERN und SPEICHERN UND SCHLIESSEN ausgegraut, obwohl Änderungen/Neueintragungen gemacht wurden. Eine Speicherung der geänderten Liste ist nicht möglich.
Weiterhin bricht die Eingabe bei der Eingabe einer IP-Adresse ab, das Einkopieren einer vollständigen Adresse ist möglich.
Ursache möglicherweise unzulässige Zeichen in der Gerätebeschreibung/Adaptername

**Comment by gsenkowski** [comment]
Danke, diese Konstellation ist interessant, wir schauen uns an was genau die Felder  SPEICHERN und SPEICHERN UND SCHLIESSEN blockiert.

**Comment by gsenkowski** [comment]
Ok ich konnte jetzt beide Fälle, mit und ohne funktionierenden Workaround, reproduzieren.

**Fall 1: Neu installierter Adapter, es wurde noch keine E Mail Adresse im Reiter "Allgemeine Einstellungen" eingegeben.**

In diesem Fall funktionieren die Workarounds **nicht** und die Felder "SPEICHERN" und "SPEICHERN UND SCHLIESSEN" bleiben ausgegraut wenn manuell ein weiteres Gerät hinzugefügt wird.

**Fall 2: Es ist bereits eine E Mail Adresse im Reiter "Allgemeine Einstellungen" eingetragen.**

In diesem Fall funktionieren die Workarounds  und die Felder "SPEICHERN" und "SPEICHERN UND SCHLIESSEN" werden aktiviert sobald manuell ein weiteres Gerät hinzugefügt wurde.
